#!/bin/bash

set -ex

if [ ! -d Paper ]; then
  git clone https://github.com/PaperMC/Paper.git Paper
fi

pushd Paper
if [[ "$(git rev-parse --abbrev-ref HEAD)" != ver/1.12.2 ]]; then
  git checkout ver/1.12.2
fi
popd
