#!/bin/bash

set -ex

if [ ! -d Paper ]; then
  git clone https://github.com/PaperMC/Paper.git Paper
fi

pushd Paper
if [[ "$(git rev-parse --abbrev-ref HEAD)" != ver/1.12.2 ]]; then
  git checkout ver/1.12.2
fi
popd

pushd Paper
git reset Spigot-Server-Patches
git clean -df Spigot-Server-Patches
popd
find patches -mindepth 1 -maxdepth 1 -type f -print0 | xargs -0 -I {} cp -v {} Paper/Spigot-Server-Patches

pushd Paper
./paper jar
popd

cp -v Paper/paperclip.jar Yukkit.jar
