#!/bin/bash

set -ex

./init

pushd Paper
git clean -df Spigot-Server-Patches
popd

last_index="$(ls Paper/Spigot-Server-Patches | tail -1 | cut -d - -f 1)"

for patch in patches/*.patch; do
  index="$(basename $patch | cut -d - -f 1)"
  next_index="$(printf '%04g\n' "$(expr $last_index + 1 + $index)")"
  cp -v "$patch" Paper/Spigot-Server-Patches/"$next_index"-"$(basename $patch | cut -d - -f 2-)"
done

cd Paper
if [[ "$(git rev-parse --abbrev-ref HEAD)" != ver/1.12.2 ]]; then
  git checkout ver/1.12.2
fi
./paper patch
