#!/bin/bash

set -ex

./init

pushd Paper
git reset Spigot-Server-Patches
git clean -df Spigot-Server-Patches
popd

find patches -mindepth 1 -maxdepth 1 -type f -print0 | xargs -0 -I {} cp -v {} Paper/Spigot-Server-Patches

cd Paper
./paper patch
