#!/bin/bash

set -ex

./init

pushd Paper
./paper rebuild
patches="$(git diff-index origin/ver/1.12.2 --name-only Spigot-Server-Patches)"
popd

rm -fv patches/*
echo "$patches" | xargs -I {} cp -v Paper/{} patches
