#!/bin/bash

set -ex

function load {
  if [ ! -d Paper ]; then
    git clone -b ver/1.12.2 https://github.com/PaperMC/Paper.git Paper
  fi
  (
    cd Paper
    git fetch origin ver/1.12.2
    git switch -C ver/1.12.2 origin/ver/1.12.2
    if [ -d ../patches/paper ]; then
      find ../patches/paper -mindepth 1 -maxdepth 1 -type f -print0 | xargs -0 git am -3
    fi
  )
  if [ ! -d Yukkit-Core ]; then
    git clone https://github.com/YukiLeafX/Yukkit-Core.git
  fi
  (
    cd Yukkit-Core
    git fetch origin master
    git switch -C master origin/master
    ./gradlew --console=plain --no-daemon publishToMavenLocal
  )
}

function apply {
  if [ ! -d Paper ]; then
    return
  fi
  (
    cd Paper
    ./paper patch
  )
}

function save {
  if [ ! -d Paper ]; then
    return
  fi
  (
    cd Paper
    find ../patches/paper -mindepth 1 -maxdepth 1 -type f -print0 | xargs -0 rm -f
    git format-patch -o ../patches/paper -pN --zero-commit origin/ver/1.12.2
  )
  (
    cd Yukkit-API
    find ../patches/yukkit-api -mindepth 1 -maxdepth 1 -type f -print0 | xargs -0 rm -f
    git format-patch -o ../patches/yukkit-api -pN --zero-commit upstream/upstream
  )
  (
    cd Yukkit-Server
    find ../patches/yukkit-server -mindepth 1 -maxdepth 1 -type f -print0 | xargs -0 rm -f
    git format-patch -o ../patches/yukkit-server -pN --zero-commit upstream/upstream
  )
}

function build {
  mvn -B clean install
}

function clip {
  mvn -B -f Paper/work/Paperclip/pom.xml -Dmcver=1.12.2 -Dpaperjar=../../../../Yukkit-Server/target/yukkit-server-1.12.2-R0.1-SNAPSHOT.jar -Dvanillajar=../../Minecraft/1.12.2/1.12.2.jar clean package
  cp -v Paper/work/Paperclip/assembly/target/paperclip-1.12.2.jar Yukkit.jar
}

function jar {
  load
  apply
  build
  clip
}

function usage {
  echo -e "Usage >> \e[1;31m$0 [ load | apply | build | clip | jar | save ]\e[m"
}

case "$1" in
  load | init ) load ;;
  apply | patch ) apply ;;
  build ) build ;;
  clip ) clip ;;
  jar ) jar ;;
  save ) save ;;
  * ) usage ;;
esac
