#!/bin/bash

set -ex

function load {
  if [ ! -d Paper ]; then
    git clone -b ver/1.12.2 https://github.com/PaperMC/Paper.git Paper
  fi
  (
    cd Paper
    git switch --detach ver/1.12.2
    if [ -d ../patches/custom ]; then
      find ../patches/custom -mindepth 1 -maxdepth 1 -type f -print0 | xargs -0 git am
    fi
    ./paper patch
  )
}

function save {
  if [ -d Paper ]; then
    (
      cd Paper
      find ../patches/custom -mindepth 1 -maxdepth 1 -type f -print0 | xargs -0 rm
      git format-patch -o ../patches/custom --no-stat --no-numbered --zero-commit ver/1.12.2
    )
  fi
}

"$@"
