#!/bin/bash

set -ex

function load {
  if [ ! -d Paper ]; then
    git clone -b ver/1.12.2 https://github.com/PaperMC/Paper.git Paper
  fi
  (
    cd Paper
    git switch -C ver/1.12.2 origin/ver/1.12.2
    if [ -d ../patches/custom ]; then
      find ../patches/custom -mindepth 1 -maxdepth 1 -type f -print0 | xargs -0 git am -3
    fi
    ./paper patch
  )
}

function save {
  if [ ! -d Paper ]; then
    return
  fi
  (
    cd Paper
    find ../patches/custom -mindepth 1 -maxdepth 1 -type f -print0 | xargs -0 rm -f
    git format-patch -o ../patches/custom --no-stat --no-numbered --zero-commit origin/ver/1.12.2
  )
  (
    cd Yukkit-API
    find ../patches/yukkit-api -mindepth 1 -maxdepth 1 -type f -print0 | xargs -0 rm -f
    git format-patch -o ../patches/yukkit-api --no-stat --no-numbered --zero-commit upstream/upstream
  )
  (
    cd Yukkit-Server
    find ../patches/yukkit-server -mindepth 1 -maxdepth 1 -type f -print0 | xargs -0 rm -f
    git format-patch -o ../patches/yukkit-server --no-stat --no-numbered --zero-commit upstream/upstream
  )
}

function jar {
  load
  if [ -n "$1" ] && [ -n "$2" ]; then
    git tag -a "$1" -m "$2"
  fi
  mvn -B clean install
  mvn -B -f Paper/work/Paperclip/pom.xml -Dmcver=1.12.2 -Dpaperjar=../../../../Yukkit-Server/target/yukkit-1.12.2.jar -Dvanillajar=../../Minecraft/1.12.2/1.12.2.jar clean package
  cp -v Paper/work/Paperclip/assembly/target/paperclip-1.12.2.jar Yukkit.jar
}

"$@"
