weight = 0

['system property']
# (https://account.mojang.com/documents/minecraft_eula)
'com.mojang.eula.agree' = true
# (https://github.com/PaperMC/Paper/issues/895#issuecomment-353785832)
'paper.playerconnection.keepalive' = 60
# Yukkit
'yukkit.suppress-recipe-warning' = "com.shampaggon.crackshot.CSMinion.customRecipes"

['server.properties']
# (https://www.spigotmc.org/threads/guide-server-optimization%E2%9A%A1.283181/)
view-distance = 7
# Yukkit
max-players = 2020
# Yukkit
motd = "\u00a77// \u00a7aYukkit\u00a77 //\n\u00a7f\u00a7nUser friendly and flexible Paper fork."

['bukkit.yml']
# (https://www.spigotmc.org/threads/is-there-a-way-to-save-worlds-in-a-separate-folder.336336/#post-3132682)
'settings.world-container' = "worlds"
# (https://www.spigotmc.org/wiki/reducing-lag/)
'chunk-gc.period-in-ticks' = 300
# (https://www.spigotmc.org/wiki/reducing-lag/)
'chunk-gc.load-threshold' = 300

['spigot.yml']
# (https://www.spigotmc.org/threads/guide-server-optimization%E2%9A%A1.283181/)
'settings.save-user-cache-on-stop-only' = true
# (https://www.spigotmc.org/wiki/reducing-lag/)
'world-settings.default.entity-activation-range.animals' = 8
# (https://www.spigotmc.org/wiki/reducing-lag/)
'world-settings.default.entity-activation-range.monsters' = 24
# (https://www.spigotmc.org/wiki/reducing-lag/)
'world-settings.default.entity-activation-range.misc' = 2
# Yukkit
'world-settings.default.entity-activation-range.water' = 4
# (https://www.spigotmc.org/threads/guide-server-optimization%E2%9A%A1.283181/)
'world-settings.default.entity-activation-range.tick-inactive-villagers' = false
# (https://aikar.co/2015/10/08/spigot-tick-limiter-dont-use-max-tick-time/)
'world-settings.default.max-tick-time.tile' = 1000
# (https://aikar.co/2015/10/08/spigot-tick-limiter-dont-use-max-tick-time/)
'world-settings.default.max-tick-time.entity' = 1000
# (https://www.reddit.com/r/admincraft/comments/freod9/spigotpaper_if_you_have_players_who_use_tnt/)
'world-settings.default.max-tnt-per-tick' = 500
# (https://stackoverflow.com/a/30371225)
'settings.netty-threads' = 12

['paper.yml']
# Yukkit
'settings.max-player-auto-save-per-tick' = 2
# (https://www.spigotmc.org/threads/guide-server-optimization%E2%9A%A1.283181/)
'world-settings.default.max-auto-save-chunks-per-tick' = 6
# (https://www.spigotmc.org/threads/guide-server-optimization%E2%9A%A1.283181/)
'world-settings.default.hopper.disable-move-event' = true
# (https://www.spigotmc.org/threads/guide-server-optimization%E2%9A%A1.283181/)
'world-settings.default.prevent-moving-into-unloaded-chunks' = true
# (https://www.spigotmc.org/threads/guide-server-optimization%E2%9A%A1.283181/)
'world-settings.default.optimize-explosions' = true
# (https://www.spigotmc.org/threads/guide-server-optimization%E2%9A%A1.283181/)
'world-settings.default.armor-stands-tick' = false
# (https://github.com/PaperMC/Paper/issues/674#issuecomment-357852383)
'world-settings.default.max-chunk-sends-per-tick' = 20
# Yukkit
'world-settings.default.max-chunk-gens-per-tick' = 2
