name: Yukkit

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: git config --global user.name 'GitHub Actions'
      - run: git config --global user.email actions@github.com
      - run: git config --global --list
      - run: ./yukkit fetch
      - run: ./yukkit patch
      - run: "git tag --annotate --message='Build #${{ github.run_number }}' '#${{ github.run_number }}'"
      - run: ./yukkit build
      - run: ./yukkit clip
        if: github.ref == 'refs/heads/stable'
      - uses: actions/create-release@v1
        if: github.ref == 'refs/heads/stable'
        id: release
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          tag_name: '#${{ github.run_number }}'
          release_name: 'Build #${{ github.run_number }} - Stable'
      - uses: actions/upload-release-asset@v1
        if: github.ref == 'refs/heads/stable'
        id: upload-jar
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          upload_url: '${{ steps.release.outputs.upload_url }}'
          asset_path: Yukkit.jar
          asset_name: Yukkit.jar
          asset_content_type: application/octet-stream
