name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: git config --global user.name "GitHub Actions"
      - run: git config --global user.email "actions@github.com"
      - run: ./yuki load
