name: Install

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "8"
      - run: sudo apt -y update
      - run: sudo apt -y install jq
      - run: ./build install
