name: Install

on:
  push:
    branches: [ master ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - { uses: actions/checkout@v2 }
      - { uses: actions/setup-java@v1, with: { java-version: 8 } }
      - { uses: actions/setup-python@v1, with: { python-version: 3 } }
      - { run: pip install -r requirements.txt }
      - { run: ./build install }
