name: Release

on:
  push:
    branches: [ release ]

jobs:
  jar:
    runs-on: ubuntu-latest
    steps:
      - { uses: actions/checkout@v2 }
      - { uses: actions/setup-java@v1, with: { java-version: 8 } }
      - { run: git config --global user.name 'Github Actions' }
      - { run: git config --global user.email 'actions@github.com' }
      - { uses: actions/cache@v1, with: { path: ~/.m2/repository, key: '${{ runner.os }}-m2-jar' } }
      - { run: ./build jar }
      - { uses: actions/create-release@v1, id: release, env: { GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}' }, with: { tag_name: 'b${{ github.run_number }}', release_name: 'Release b${{ github.run_number }}' } }
      - { uses: actions/upload-release-asset@v1, id: upload-jar, env: { GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}' }, with: { upload_url: '${{ steps.release.outputs.upload_url }}', asset_path: Yukkit.jar, asset_name: Yukkit.jar, asset_content_type: application/octet-stream } }
